name: Freedom
main: me.adapt.freedom.core.Freedom
version: 1.3
author: [Adaptified]
description: The newest Freedom plugin by adaptified
softdepend: [Aero, CoreProtect]
commands:
    rollback:
        description: Roll a player back
        usage: /<command> <player> 
        aliases: [rb]
    rollbackundo:
        description: Roll a player back
        usage: /<command> <player> 
        aliases: [rbu]    
    