name: Freedom
main: me.liamplugins.core.Feedom
version: 1.0
author: [DUFC_Liam]
authors: [FoxIshDaBest, Adaptified]
description: The newest Freedom plugin by DUFC_Liam, FoxIshDaBest, and Adaptified.
softdepend: [Aero, CoreProtect]
commands:
    rollback:
        description: Roll a player back
        usage: /<command> <player> 
        aliases: [rb]
    rollbackundo:
        description: Roll a player back
        usage: /<command> <player> 
        aliases: [rbu]    
    
