 name: Freedom
 version: 0.1.0
 description: A whole new aspect to freedom
 author: IllX
 authors: [DUFC_Liam] 
 
 main: me.freedom.Freedom
 database: false
 depend: []
 
 commands:
   BLANK:
     description: BLANK
     aliases: []
     usage: Syntax error! Simply type /&lt;blank&gt; to use this!.
     
